```java
/**
 * Problem: Walking Robot Simulation II
 * Summary: Simulates a robot moving on a grid, turning when hitting boundaries.
 * Link: https://leetcode.com/problems/walking-robot-simulation-ii/
 *
 * Approach:
 * The core idea is to simulate the robot's movement and turns. We can represent the robot's state
 * using its current x-coordinate, y-coordinate, and direction. The directions can be mapped to
 * integers (0: East, 1: North, 2: West, 3: South) to simplify direction changes.
 * When the `step(num)` method is called, we iterate `num` times. In each step, we try to move
 * one unit in the current direction. Before moving, we check if the next position would be out of bounds.
 * If it is out of bounds, the robot turns 90 degrees counterclockwise. Otherwise, the robot moves to
 * the new cell.
 *
 * To optimize repeated `step` calls and the potential for large `num` values, we can pre-calculate
 * the full path the robot would take around the perimeter of the grid. This is because the robot
 * will eventually traverse the entire perimeter multiple times before stopping at a final position.
 *
 * The perimeter path can be generated by starting at (0,0) facing East. Move East until the right
 * boundary, turn North, move North until the top boundary, turn West, move West until the left
 * boundary, turn South, move South until the bottom boundary (but not back to (0,0) if height > 1),
 * turn East, and repeat.
 *
 * We store this path as a list of (x, y) coordinates. When `step(num)` is called, we can calculate
 * the robot's final position by finding its current index in the pre-calculated path and advancing
 * `num` steps along the path, wrapping around if necessary.
 *
 * The `getPos()` and `getDir()` methods simply return the current state of the robot.
 *
 * Time Complexity:
 * - Robot(width, height): O(width * height). Generating the initial path around the perimeter takes time proportional to the perimeter, which is O(width + height). However, if the robot moves significantly, it will traverse the perimeter multiple times. The maximum number of unique positions the robot can visit before repeating a full cycle around the perimeter is 2*(width-1) + 2*(height-1). The `step` function will make a total of `num` moves. If `num` is very large, it will cycle through the perimeter path. The pre-computation of the path takes O(width + height). After pre-computation, `step(num)` takes O(1) because we can calculate the final position using modulo arithmetic on the path length. `getPos` and `getDir` are O(1).
 * - Overall, if we consider the total number of steps made across all `step` calls, the pre-computation is O(width+height) and each `step` operation after pre-computation is O(1). The total number of calls is limited, so the total time complexity is dominated by the initial path generation and the total number of moves.
 *
 * Space Complexity:
 * - O(width * height). We store the path of the robot, which can have up to 2*(width-1) + 2*(height-1) positions in one full cycle.
 */
class Robot {
    private int width;
    private int height;
    private int x;
    private int y;
    private int dir; // 0: East, 1: North, 2: West, 3: South
    private String[] directions = {"East", "North", "West", "South"};

    // Store the pre-calculated path of the robot around the perimeter.
    // Each element is an int array [x, y].
    private java.util.List<int[]> path;
    private int currentPathIndex; // The index in the 'path' list where the robot is currently.

    /**
     * Initializes the robot and the grid.
     * @param width The width of the grid.
     * @param height The height of the grid.
     */
    public Robot(int width, int height) {
        this.width = width;
        this.height = height;
        this.x = 0;
        this.y = 0;
        this.dir = 0; // Initially facing East
        this.currentPathIndex = 0;

        // Pre-calculate the path of the robot around the perimeter.
        this.path = new java.util.ArrayList<>();
        generatePath();
    }

    /**
     * Generates the complete path the robot will take around the grid's perimeter.
     * This path is cyclical.
     */
    private void generatePath() {
        // Start at (0,0) facing East
        int currentX = 0;
        int currentY = 0;
        int currentDir = 0; // 0: East, 1: North, 2: West, 3: South

        // Add the starting position.
        path.add(new int[]{currentX, currentY});

        // Simulate movement around the perimeter until we've completed a full cycle
        // or the path size exceeds the maximum possible unique positions.
        // The maximum number of unique positions is 2*(width-1) + 2*(height-1) + 1 (for starting point).
        // We can use a large enough limit to ensure we capture at least one full cycle.
        int maxPathLength = 2 * (width - 1) + 2 * (height - 1) + 2; // Add some buffer

        while (path.size() < maxPathLength) {
            int nextX = currentX;
            int nextY = currentY;

            // Determine next potential move based on direction
            if (currentDir == 0) nextX++; // East
            else if (currentDir == 1) nextY++; // North
            else if (currentDir == 2) nextX--; // West
            else if (currentDir == 3) nextY--; // South

            boolean outOfBounds = false;
            // Check boundary conditions
            if (nextX < 0 || nextX >= width || nextY < 0 || nextY >= height) {
                outOfBounds = true;
            }

            if (outOfBounds) {
                // Turn 90 degrees counterclockwise
                currentDir = (currentDir + 1) % 4;
                // Retry the step in the new direction. If we are at (0,0) and just turned South
                // from East, then try to move South. If we are at (width-1, 0) and just turned North
                // from East, then try to move North.
                // We need to be careful not to get stuck in an infinite loop if width or height is 1.
                // However, constraints state width, height >= 2, so this is not an issue.
            } else {
                // Move to the new position
                currentX = nextX;
                currentY = nextY;
                path.add(new int[]{currentX, currentY});

                // If we return to (0,0) after the first move, it means we've completed a full loop.
                // This check is important to stop generating the path if it cycles back.
                // However, the problem implies movement continues indefinitely, so we generate
                // a long enough path to cover many steps.
                // A simpler stopping condition: stop if we've already visited this position and direction combination.
                // But for simulation, we assume `num` can be very large, so we need a path that's
                // long enough to cover `num` steps or repeats.
                // The crucial part is that the path eventually repeats its sequence of positions and directions.
                // The length of this cycle is 2*(width-1) + 2*(height-1).
                if (currentX == 0 && currentY == 0 && path.size() > 1) {
                    // This signifies a full cycle around the perimeter.
                    // For very large num, we only need path length of one cycle.
                    // However, to make step() O(1), we need to ensure the currentPathIndex
                    // can be advanced by `num` correctly by using modulo.
                    // The number of unique states (position + direction) is not just the perimeter length.
                    // A better approach for step is to calculate final position based on modulo of path.size().
                    // The path list will store one full cycle of movements.
                    break; // Stop after one full cycle around the perimeter.
                }
            }
        }
        // After generating the path, set the robot's initial state to match the path.
        // The robot starts at (0,0) facing East. This is already handled by initialization.
        // We just need to ensure that when step() is called for the first time,
        // currentPathIndex is 0, which it is.
    }


    /**
     * Instructs the robot to move forward num steps.
     * @param num The number of steps to move.
     */
    public void step(int num) {
        // The total number of steps the robot will take is `num`.
        // We can determine the final position by advancing our current index in the pre-calculated path.

        // Get the length of one full cycle of the path.
        int pathLength = path.size();

        // If the robot is at the end of the pre-calculated path (meaning it just completed a cycle),
        // and its position is (0,0), and it just turned East, it means it's ready to start a new cycle.
        // The `generatePath` should ensure the path covers at least one full cycle if the robot
        // continues moving.
        // The `currentPathIndex` tracks where the robot is in the *current traversal* of the path.
        // If it reaches the end of `path` list, it wraps around.

        // Calculate the target index after `num` steps.
        // We need to handle the case where the robot is at (0,0) facing East, which is path index 0.
        // If the path length is L, then after `num` steps, the new index will be (currentPathIndex + num) % L.
        // However, we need to be careful: the path might not be exactly L steps to return to the start state.
        // The `generatePath` should ideally stop after one full cycle such that the state after the last
        // element is the same as the state of the first element (but one step later).

        // Let's re-evaluate `generatePath` and how `step` uses it.
        // The robot moves `num` steps. We can think of this as moving `num` positions along the cyclical path.
        // `currentPathIndex` should represent the index of the *next* position the robot will occupy.
        // If the robot is at index `i`, and takes `num` steps, it will end up at index `(i + num) % path.size()`.

        // Handle the case where the robot is at (0,0) and `num` is 0.
        if (num == 0) {
            return;
        }

        // The `currentPathIndex` is the index of the *current* position.
        // After `num` steps, the new index will be `(currentPathIndex + num) % path.size()`.
        // However, the `path` list might have been generated for one full cycle.
        // We need to ensure `currentPathIndex` is correctly maintained.

        // The problem statement implies that `step(num)` moves the robot `num` units.
        // If the robot is at position `P` in the `path` list and `num` steps are taken,
        // the final position will be `(P + num) % path.size()`.
        // The `currentPathIndex` is the index of the robot's current position *within the pre-calculated path*.

        // If `path.size()` is 1 (e.g., 2x2 grid, first step), this logic might be tricky.
        // For a 2x2 grid:
        // Path: (0,0) E, (1,0) E, turn N, (1,1) N, turn W, (0,1) W, turn S, (0,0) S - but this state is (0,0) facing East.
        // The path length should represent the number of distinct *moves* or *positions visited before repeating state*.
        // The `generatePath` function correctly adds positions.
        // The number of distinct positions visited in a full cycle around the perimeter is `2 * (width - 1) + 2 * (height - 1)`.
        // Let `cycleLength = 2 * (width - 1) + 2 * (height - 1)`.
        // Our `path` list contains these positions, starting from (0,0).
        // The size of `path` after `generatePath` should be `cycleLength + 1` (including the start).
        // If the robot is at `currentPathIndex` and takes `num` steps, its new index is `(currentPathIndex + num) % path.size()`.
        // However, `path.size()` might be exactly `cycleLength` if `generatePath` breaks after reaching (0,0).
        // Let's refine `generatePath`'s break condition. It should stop once it completes one full cycle of unique movements.
        // The number of unique movements before repeating the start state (0,0, East) is `2*(width-1) + 2*(height-1)`.
        // So, the path list should have `2*(width-1) + 2*(height-1)` elements, representing the positions visited after each step.

        // Let's trace with example 1: width=6, height=3.
        // Cycle length = 2*(6-1) + 2*(3-1) = 2*5 + 2*2 = 10 + 4 = 14 steps.
        // Path should have 14 positions (steps) + start = 15 elements.
        // (0,0) E -> (1,0) E -> (2,0) E -> (3,0) E -> (4,0) E -> (5,0) E (hits boundary)
        // Turn N. (5,0) N -> (5,1) N -> (5,2) N (hits boundary)
        // Turn W. (5,2) W -> (4,2) W -> (3,2) W -> (2,2) W -> (1,2) W -> (0,2) W (hits boundary)
        // Turn S. (0,2) S -> (0,1) S -> (0,0) S (hits boundary). Robot is at (0,0) facing South.
        // Turn E. (0,0) E. This is the start state. So, 14 steps complete a cycle.
        // The `path` list will contain 15 elements: (0,0), (1,0), ..., (0,2), (0,1).
        // The last element is (0,1). The next step would be to (0,0) facing South. Then turn East.

        // The `currentPathIndex` refers to the index of the robot's *current position* in the `path` list.
        // So, if `path.size()` is `N`, indices are `0` to `N-1`.
        // If robot is at `currentPathIndex`, and takes `num` steps, it will advance `num` positions.
        // The new index will be `(currentPathIndex + num) % N`.

        int pathCycleLength = path.size(); // The total number of positions in one full cycle.
                                           // This should be 2*(width-1) + 2*(height-1) + 1 (for the start).

        // The robot is currently at the position `path.get(currentPathIndex)`.
        // After `num` steps, it will be at a new index.
        // If `num` is large, it will wrap around the `path` multiple times.
        // The number of steps to take along the path is `num`.
        // The effective index will be `(currentPathIndex + num) % pathCycleLength`.
        currentPathIndex = (currentPathIndex + num) % pathCycleLength;

        // Update the robot's current position and direction based on the new index.
        int[] newPos = path.get(currentPathIndex);
        this.x = newPos[0];
        this.y = newPos[1];

        // Determine the direction. The direction depends on which segment of the path we are in.
        // If currentPathIndex is 0, it's (0,0) facing East.
        // If currentPathIndex is 1, it's (1,0) facing East.
        // If currentPathIndex is `k` and it's on the Eastward path, the direction is East.
        // The direction is determined by the step that *led* to this position.
        // Or more simply, the direction at a path index `i` is the direction that would move us to `path.get(i+1)`.
        // If `i == pathCycleLength - 1`, the next step is `path.get(0)`.

        // Let's refine direction calculation.
        // The direction is static for a segment of the path.
        // If we are at `currentPathIndex`:
        // If `currentPathIndex == 0` (start position), direction is East.
        // If `path.get(currentPathIndex)[0] > path.get(currentPathIndex - 1)[0]`, we moved East.
        // If `path.get(currentPathIndex)[1] > path.get(currentPathIndex - 1)[1]`, we moved North.
        // If `path.get(currentPathIndex)[0] < path.get(currentPathIndex - 1)[0]`, we moved West.
        // If `path.get(currentPathIndex)[1] < path.get(currentPathIndex - 1)[1]`, we moved South.
        // This is complex. A simpler way:
        // The direction is determined by where we *were* when we took the last step.
        // The `generatePath` simulation implicitly defines the direction for each move.
        // We need to store the direction along with the position in the path.
        // Or, we can deduce it:
        // If `path.get(currentPathIndex)` is `(x, y)` and `path.get((currentPathIndex + 1) % pathCycleLength)` is `(x', y')`:
        // The direction is determined by the transition from (x,y) to (x',y').
        // If x' = x+1, direction is East. If x' = x-1, direction is West.
        // If y' = y+1, direction is North. If y' = y-1, direction is South.
        // This implies the direction is the one that *leads away* from the current position towards the next.

        // Example: path.get(0)=(0,0), path.get(1)=(1,0). Next step from (0,0) to (1,0) is East.
        // So at index 0, the direction is East.
        // At index 1, path.get(1)=(1,0), path.get(2)=(2,0). Next step from (1,0) to (2,0) is East.
        // So at index 1, direction is East.
        // ...
        // At index where it hits boundary: path.get(k) = (5,0), path.get(k+1) = (5,1) after turning North.
        // The move from (5,0) to (5,1) is North. So, at index k, the direction is North.

        // Let's determine the direction based on the *current* position and where the *next* step in the cycle would go.
        int nextIndexInPath = (currentPathIndex + 1) % pathCycleLength;
        int[] nextPos = path.get(nextIndexInPath);

        if (nextPos[0] == this.x + 1) {
            this.dir = 0; // East
        } else if (nextPos[1] == this.y + 1) {
            this.dir = 1; // North
        } else if (nextPos[0] == this.x - 1) {
            this.dir = 2; // West
        } else if (nextPos[1] == this.y - 1) {
            this.dir = 3; // South
        } else {
            // This case should ideally not happen if the path is generated correctly and the robot is on the path.
            // It might occur if the robot is at the very end of the path and the next step is to wrap around.
            // In that case, the direction logic based on `nextPos` will still work if `pathCycleLength` is correctly calculated.
            // Example: if path ends at (0,1) and wraps to (0,0), this logic would deduce South for (0,1) -> (0,0).
            // This is correct because when robot is at (0,1) facing South, the next step would be (0,0).
        }
        
        // Special case: if we are at (0,0) after a full cycle and the path generated stopped.
        // If `currentPathIndex` is 0 and `path.size()` is exactly `2*(width-1) + 2*(height-1) + 1`,
        // and `num` was large enough to wrap around.
        // The direction for `currentPathIndex = 0` should be East.
        // Our deduction logic: `path.get(0)=(0,0)`, `path.get(1)=(1,0)`. Next step is East. So `dir=0`. This is correct.
    }

    /**
     * Returns the current cell the robot is at.
     * @return An array of length 2, [x, y].
     */
    public int[] getPos() {
        return new int[]{this.x, this.y};
    }

    /**
     * Returns the current direction of the robot.
     * @return The direction as a String ("North", "East", "South", or "West").
     */
    public String getDir() {
        return directions[this.dir];
    }
}
```