// Load environment variables from .env file (for local testing)
require('dotenv').config();

const axios = require('axios');
const { GoogleGenerativeAI } = require('@google/generative-ai');
const fs = require('fs');
const path = require('path');

// Initialize Google Gemini AI
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash-exp" });

/**
 * Fetch the daily LeetCode problem
 * Note: LeetCode doesn't have an official public API, so we'll use GraphQL endpoint
 */
async function getDailyProblem() {
    try {
        const query = `
      query questionOfToday {
        activeDailyCodingChallengeQuestion {
          date
          link
          question {
            questionId
            title
            titleSlug
            content
            difficulty
            exampleTestcases
            topicTags {
              name
            }
          }
        }
      }
    `;

        const response = await axios.post('https://leetcode.com/graphql', {
            query: query,
            variables: {}
        }, {
            headers: {
                'Content-Type': 'application/json',
                'Referer': 'https://leetcode.com'
            }
        });

        const data = response.data.data.activeDailyCodingChallengeQuestion;
        return {
            date: data.date,
            title: data.question.title,
            titleSlug: data.question.titleSlug,
            difficulty: data.question.difficulty,
            content: data.question.content,
            link: `https://leetcode.com${data.link}`,
            topicTags: data.question.topicTags.map(tag => tag.name),
            exampleTestcases: data.question.exampleTestcases
        };
    } catch (error) {
        console.error('Error fetching daily problem:', error.message);
        throw error;
    }
}

/**
 * Clean HTML content from problem description
 */
function cleanHTML(html) {
    return html
        .replace(/<[^>]*>/g, '')
        .replace(/&nbsp;/g, ' ')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&amp;/g, '&')
        .replace(/&quot;/g, '"')
        .trim();
}

/**
 * Use Google Gemini AI to generate a solution
 */
async function generateSolution(problem) {
    try {
        const cleanContent = cleanHTML(problem.content);

        const prompt = `You are an expert programmer solving LeetCode problems. 

Problem: ${problem.title}
Difficulty: ${problem.difficulty}
Topics: ${problem.topicTags.join(', ')}

Description:
${cleanContent}

Please provide:
1. A well-commented JavaScript solution
2. Time complexity analysis
3. Space complexity analysis
4. Brief explanation of the approach

Format your response as a complete JavaScript file with comments.`;

        const result = await model.generateContent(prompt);
        const response = await result.response;
        return response.text();
    } catch (error) {
        console.error('Error generating solution:', error.message);
        throw error;
    }
}

/**
 * Save solution to file
 */
function saveSolution(problem, solution) {
    const solutionsDir = path.join(__dirname, '../solutions');

    // Create solutions directory if it doesn't exist
    if (!fs.existsSync(solutionsDir)) {
        fs.mkdirSync(solutionsDir, { recursive: true });
    }

    // Create filename from date and problem title
    const filename = `${problem.date}-${problem.titleSlug}.js`;
    const filepath = path.join(solutionsDir, filename);

    // Create file content with metadata
    const fileContent = `/**
 * LeetCode Daily Challenge - ${problem.date}
 * 
 * Problem: ${problem.title}
 * Difficulty: ${problem.difficulty}
 * Link: ${problem.link}
 * Topics: ${problem.topicTags.join(', ')}
 * 
 * Generated by AI on ${new Date().toISOString()}
 */

${solution}
`;

    fs.writeFileSync(filepath, fileContent, 'utf8');
    console.log(`✅ Solution saved to: ${filename}`);

    return filepath;
}

/**
 * Main function
 */
async function main() {
    try {
        console.log('🚀 Starting Daily LeetCode Solver...\n');

        // Check if API key is set
        if (!process.env.GEMINI_API_KEY) {
            throw new Error('GEMINI_API_KEY environment variable is not set');
        }

        // Fetch daily problem
        console.log('📥 Fetching daily LeetCode problem...');
        const problem = await getDailyProblem();
        console.log(`✅ Found problem: ${problem.title} (${problem.difficulty})\n`);

        // Generate solution
        console.log('🤖 Generating AI solution...');
        const solution = await generateSolution(problem);
        console.log('✅ Solution generated\n');

        // Save solution
        console.log('💾 Saving solution...');
        const filepath = saveSolution(problem, solution);

        console.log('\n✨ Done! Solution ready for commit.');

    } catch (error) {
        console.error('❌ Error:', error.message);
        process.exit(1);
    }
}

// Run the script
main();
